import Link from "next/link";
import { DateTime } from "luxon";
import { getStaffSchedule } from "@/features/bookings/queries";
import { getCurrentProfile } from "@/lib/auth/session";
import { formatManilaTime } from "@/lib/format";
import { RealtimeRefresh } from "@/components/realtime-refresh";
import { getServerEnv } from "@/lib/env/server";
export const metadata={title:"Today"};
export const instant=false;
export default async function StaffTodayPage(){const profile=await getCurrentProfile();const now=DateTime.now().setZone("Asia/Manila");const start=now.startOf("day");const bookings=await getStaffSchedule(profile.id,{startsAt:start.toUTC().toJSDate(),endsAt:start.plus({days:1}).toUTC().toJSDate()});const upcoming=bookings.find(item=>item.requestedEndsAt>new Date());const env=getServerEnv();return <div><RealtimeRefresh url={env.SUPABASE_URL} publishableKey={env.SUPABASE_PUBLISHABLE_KEY} topics={[`schedule:${now.toISODate()}`,"schedule:all"]}/><p className="text-sm font-semibold text-brand-800">{now.toFormat("cccc, d LLLL")}</p><h1 className="text-h1 mt-1">Your day</h1>{upcoming&&<section className="mt-7 rounded-3xl bg-brand-950 p-6 text-white"><p className="text-sm font-semibold text-white/65">{upcoming.requestedStartsAt>new Date()?"Next appointment":"In progress"}</p><div className="mt-4 grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="tabular text-3xl font-semibold">{formatManilaTime(upcoming.requestedStartsAt)}</p><h2 className="mt-3 text-xl font-semibold">{upcoming.customerName}</h2><p className="mt-1 text-sm text-white/70">{upcoming.services.map(x=>x.serviceName).join(", ")}</p></div><Link href={`/portal/staff/bookings/${upcoming.id}`} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white px-5 font-semibold text-brand-950">Open appointment</Link></div></section>}<section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-h2">Today’s assignments</h2><Link href="/portal/staff/schedule" className="text-sm font-semibold text-brand-800">Full schedule</Link></div><div className="mt-4 overflow-hidden rounded-2xl border border-line bg-surface">{bookings.length?bookings.map(booking=><Link key={booking.id} href={`/portal/staff/bookings/${booking.id}`} className="grid grid-cols-[72px_1fr_auto] gap-3 border-b border-line p-4 last:border-0 hover:bg-brand-50"><p className="tabular font-semibold text-brand-900">{formatManilaTime(booking.requestedStartsAt)}</p><div><p className="font-semibold">{booking.customerName}</p><p className="mt-1 text-sm text-ink-muted">{booking.services.map(x=>x.serviceName).join(", ")}</p></div><span className="text-sm font-semibold text-ink-subtle">Open</span></Link>):<div className="p-6"><h2 className="font-semibold">No assignments today</h2><p className="mt-2 text-sm text-ink-muted">Your confirmed appointments will appear here.</p></div>}</div></section></div>}
