"use client";

import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ArrowRight, CheckCircle, CircleNotch, Phone, ShieldCheck, User, Wallet } from "@phosphor-icons/react";
import { createBookingHold } from "@/features/bookings/actions";
import { requestBookingOtp, verifyBookingOtp } from "@/features/verification/actions";
import { formatMoney } from "@/lib/format";

gsap.registerPlugin(useGSAP);

type Props = { serviceIds:string[];startsAt:string;subtotalCentavos:number;depositCentavos:number;gcashName:string|null;gcashNumber:string|null;holdDurationMinutes:number;policyVersion:string };
type ActiveAction = "requesting" | "checking" | "securing" | null;
function toE164(value:string){const entered=value.trim();return entered.startsWith("+63")?entered:`+63${entered.replace(/^0/,"")}`}
function LoadingLabel({children}:{children:React.ReactNode}){return <><CircleNotch aria-hidden className="animate-spin" size={18}/><span>{children}</span></>}

export function BookingDetailsForm(props:Props){
  const formRef=useRef<HTMLFormElement>(null);const router=useRouter();const[pending,startTransition]=useTransition();
  const[customerName,setCustomerName]=useState("");const[phone,setPhone]=useState("");const[gcashSenderName,setGcashSenderName]=useState("");
  const[verificationId,setVerificationId]=useState<string|null>(null);const[verified,setVerified]=useState(false);const[trustedDevice,setTrustedDevice]=useState(false);const[code,setCode]=useState("");const[error,setError]=useState<string|null>(null);const[activeAction,setActiveAction]=useState<ActiveAction>(null);

  useGSAP(()=>{const media=gsap.matchMedia();media.add("(prefers-reduced-motion: no-preference)",()=>{gsap.fromTo(".booking-form-reveal",{autoAlpha:0,y:14},{autoAlpha:1,y:0,duration:.48,stagger:.07,ease:"power2.out",clearProps:"transform,opacity,visibility"})});return()=>media.revert()},{scope:formRef});
  useGSAP(()=>{const media=gsap.matchMedia();media.add("(prefers-reduced-motion: no-preference)",()=>{const target=verified?".verification-success":verificationId?".otp-panel":error?".booking-error":null;if(target)gsap.fromTo(target,{autoAlpha:0,y:10,scale:.985},{autoAlpha:1,y:0,scale:1,duration:.38,ease:"power2.out",clearProps:"transform,opacity,visibility"})});return()=>media.revert()},{dependencies:[verificationId,verified,error],scope:formRef});

  function startVerification(){setError(null);setActiveAction("requesting");startTransition(async()=>{const result=await requestBookingOtp({phone:toE164(phone)});setActiveAction(null);if(!result.ok)return setError(result.error.message);setVerificationId(result.data.verificationId);setTrustedDevice(result.data.trusted);if(result.data.trusted)setVerified(true)})}
  function verifyCode(){if(!verificationId)return;setError(null);setActiveAction("checking");startTransition(async()=>{const result=await verifyBookingOtp({verificationId,phone:toE164(phone),code});setActiveAction(null);if(!result.ok)return setError(result.error.message);setVerified(true)})}
  function submit(formData:FormData){if(!verificationId||!verified)return setError("Verify your mobile number before booking.");setError(null);setActiveAction("securing");startTransition(async()=>{const result=await createBookingHold({customerName,customerPhone:toE164(phone),gcashSenderName,serviceIds:props.serviceIds,startsAt:props.startsAt,verificationId,policyVersion:props.policyVersion,policyAccepted:formData.get("policyAccepted")==="on"});if(!result.ok){setActiveAction(null);setError(result.error.code==="SLOT_UNAVAILABLE"?"That time was just taken. Please choose another available time.":result.error.message);return}router.push(`/booking/access?code=${encodeURIComponent(result.data.bookingCode)}&token=${encodeURIComponent(result.data.guestToken)}`)})}
  function changePhone(value:string){setPhone(value);setVerified(false);setTrustedDevice(false);setVerificationId(null);setCode("");setError(null)}

  return <form ref={formRef} action={submit} autoComplete="off" className="space-y-4">
    <section className="booking-form-reveal overflow-hidden rounded-2xl border border-line bg-surface">
      <div className="flex items-start gap-3 border-b border-brand-100 bg-brand-50 px-4 py-4 sm:px-5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-brand-900 text-white"><User aria-hidden size={17}/></span><div><p className="text-[11px] font-semibold text-brand-800">Contact information</p><h2 className="mt-0.5 text-lg font-semibold">Who is this booking for?</h2></div></div>
      <div className="space-y-4 px-4 py-4 sm:px-5">
        <p className="text-sm leading-5 text-ink-muted">We use these details only for appointment, payment, and safety updates.</p>
        <div className="space-y-2"><label htmlFor="booking-contact-a" className="text-sm font-semibold">Full name</label><input id="booking-contact-a" value={customerName} onChange={event=>setCustomerName(event.target.value)} autoComplete="off" data-form-type="other" data-lpignore="true" data-1p-ignore="true" data-bwignore="true" spellCheck={false} required minLength={2} maxLength={100} className="min-h-12 w-full rounded-xl border border-line bg-surface-muted px-4 text-base"/></div>
        <div className="space-y-2"><label htmlFor="booking-contact-b" className="flex items-center gap-2 text-sm font-semibold"><Phone aria-hidden size={16}/>Mobile number</label><div className="flex gap-2"><input id="booking-contact-b" value={phone} onChange={event=>changePhone(event.target.value)} type="tel" inputMode="numeric" autoComplete="off" data-form-type="other" data-lpignore="true" data-1p-ignore="true" data-bwignore="true" required className="tabular min-h-12 min-w-0 flex-1 rounded-xl border border-line bg-surface-muted px-4 text-base" placeholder="0917 123 4567"/><button type="button" disabled={activeAction==="requesting"||phone.length<10||verified} onClick={startVerification} aria-busy={activeAction==="requesting"} className="inline-flex min-h-12 min-w-[108px] items-center justify-center gap-2 rounded-xl border border-brand-900 px-4 text-sm font-semibold text-brand-900 transition-colors disabled:opacity-60">{activeAction==="requesting"?<LoadingLabel>Sending…</LoadingLabel>:verified?<><CheckCircle aria-hidden size={17}/>Verified</>:"Send code"}</button></div><p aria-live="polite" className="min-h-10 text-xs leading-5 text-ink-muted">{activeAction==="requesting"?"Sending a secure verification code to your mobile number…":"First-time customers receive an SMS code. This device is remembered for 30 days after verification."}</p></div>
        {verificationId&&!verified&&<div className="otp-panel rounded-xl border border-info/15 bg-info-soft p-3"><div className="flex items-center justify-between gap-3"><label htmlFor="otp" className="text-sm font-semibold">Enter the six-digit code</label><span className="text-[10px] font-semibold text-info">SMS sent</span></div><p className="mt-1 text-xs text-ink-muted">Check the messages sent to {phone}.</p><div className="mt-3 flex gap-2"><input id="otp" value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="off" className="tabular min-h-12 min-w-0 flex-1 rounded-xl border border-line bg-surface px-4 text-base tracking-[.3em]"/><button type="button" disabled={activeAction==="checking"||code.length!==6} onClick={verifyCode} aria-busy={activeAction==="checking"} className="inline-flex min-h-12 min-w-[110px] items-center justify-center gap-2 rounded-xl bg-brand-900 px-4 text-sm font-semibold text-white disabled:opacity-60">{activeAction==="checking"?<LoadingLabel>Checking…</LoadingLabel>:"Verify code"}</button></div></div>}
        {verified&&<p role="status" className="verification-success flex items-center gap-2 rounded-xl border border-success/15 bg-success-soft p-3 text-sm font-semibold text-success"><span className="grid size-7 place-items-center rounded-full bg-white/70"><CheckCircle size={18} weight="fill"/></span>{trustedDevice?"Welcome back — this number is already verified.":"Number verified. You can continue with your booking."}</p>}
        <div className="space-y-2"><label htmlFor="booking-payment-a" className="text-sm font-semibold">GCash sender name</label><input id="booking-payment-a" value={gcashSenderName} onChange={event=>setGcashSenderName(event.target.value)} autoComplete="off" data-form-type="other" data-lpignore="true" data-1p-ignore="true" data-bwignore="true" spellCheck={false} required minLength={2} maxLength={100} className="min-h-12 w-full rounded-xl border border-line bg-surface-muted px-4 text-base" placeholder="Name shown in GCash"/><p className="text-xs text-ink-muted">This helps Beautyfeel match your payment without requiring a screenshot.</p></div>
      </div>
    </section>
    <section className="booking-form-reveal rounded-2xl border border-[#ead9ad] bg-warning-soft p-4 sm:p-5"><div className="flex items-start gap-3"><Wallet aria-hidden size={20}/><div><p className="text-[11px] font-semibold">Payment after continuing</p><h2 className="font-semibold">20% GCash deposit</h2></div></div><dl className="mt-4 divide-y divide-[#e7d6aa] rounded-xl bg-white/55 px-3"><div className="flex justify-between py-2.5 text-sm"><dt>Service total</dt><dd className="tabular font-medium">{formatMoney(props.subtotalCentavos)}</dd></div><div className="flex justify-between py-2.5 text-sm"><dt className="font-semibold">Deposit amount</dt><dd className="tabular font-semibold">{formatMoney(props.depositCentavos)}</dd></div></dl><p className="mt-3 text-xs leading-5">{props.gcashNumber&&props.gcashName?`Send to ${props.gcashNumber} · ${props.gcashName} after your time is held.`:"Online booking is unavailable until Beautyfeel configures its GCash account."}</p></section>
    <label className="booking-form-reveal flex items-start gap-3 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm leading-5"><input name="policyAccepted" type="checkbox" required className="mt-0.5 size-4 accent-[#174e4f]"/><span>I agree to the 20% deposit policy. Cancellations convert verified deposits to store credit valid for 12 months. Schedule changes must be requested from Beautyfeel.</span><ShieldCheck aria-hidden className="shrink-0" size={18}/></label>
    <p className="booking-form-reveal text-xs leading-5 text-ink-muted">Your selected time will be held for {props.holdDurationMinutes} minutes. Submitting does not charge you automatically.</p>
    {error&&<div role="alert" className="booking-error rounded-xl border border-danger/15 bg-danger-soft p-4 text-sm font-medium text-danger">{error}</div>}
    <button disabled={pending||!verified||!props.gcashName||!props.gcashNumber} aria-busy={activeAction==="securing"} className="booking-form-reveal flex min-h-13 w-full items-center justify-center gap-2 rounded-xl bg-brand-900 px-6 font-semibold text-white transition-colors disabled:opacity-50">{activeAction==="securing"?<LoadingLabel>Securing your appointment…</LoadingLabel>:<>Secure this appointment<ArrowRight aria-hidden size={18}/></>}</button>
  </form>
}
