import Link from "next/link";
import { Suspense } from "react";
import { ShieldCheck } from "@phosphor-icons/react/dist/ssr";
import { ServiceCatalog } from "@/components/public/service-catalog";

export const metadata={title:"Services and prices",description:"Explore Beautyfeel skin treatments, massage and spa services, lashes, and nails with clear prices and treatment times.",alternates:{canonical:"/services"}};

export default function ServicesPage(){return <main><section className="border-b border-line bg-surface"><div className="mx-auto grid max-w-[1200px] gap-8 px-4 py-14 sm:px-6 sm:py-20 lg:grid-cols-[7fr_5fr] lg:items-end"><div><p className="text-sm font-semibold text-brand-800">Services and prices</p><h1 className="text-display mt-4 max-w-2xl">Choose what feels right for this visit.</h1><p className="mt-6 max-w-[58ch] text-[17px] leading-relaxed text-ink-muted">Browse the active Beautyfeel menu. Every price and treatment time is shown before you choose your appointment.</p></div><aside className="rounded-2xl bg-brand-50 p-5"><p className="flex items-center gap-2 font-semibold text-brand-950"><ShieldCheck size={19}/> Clear deposit policy</p><p className="mt-2 text-sm leading-6 text-ink-muted">Your 20% deposit is calculated from the combined price of all selected services.</p></aside></div></section><section className="mx-auto max-w-[1200px] px-4 py-14 sm:px-6 sm:py-20"><Suspense fallback={<CatalogSkeleton/>}><ServiceCatalog/></Suspense></section><section className="border-t border-line bg-brand-950 text-white"><div className="mx-auto grid max-w-[1200px] gap-6 px-4 py-12 sm:px-6 md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="text-h2">Ready to choose a time?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">Select one or more treatments and we will show times that fit your complete visit.</p></div><Link href="/book" className="inline-flex min-h-13 items-center justify-center rounded-xl bg-white px-6 font-semibold text-brand-950">Start booking</Link></div></section></main>}

function CatalogSkeleton(){return <div className="space-y-14">{[1,2].map(group=><div key={group}><div className="grid gap-5 border-b border-line pb-6 sm:grid-cols-[180px_1fr]"><div className="skeleton aspect-[3/2] rounded-2xl"/><div className="self-end"><div className="skeleton h-9 w-48 rounded-lg"/><div className="skeleton mt-3 h-5 max-w-lg rounded"/></div></div><div className="divide-y divide-line">{[1,2,3].map(item=><div key={item} className="grid gap-4 py-6 sm:grid-cols-[1fr_auto]"><div><div className="skeleton h-6 w-44 rounded"/><div className="skeleton mt-3 h-4 max-w-xl rounded"/></div><div className="skeleton h-7 w-24 rounded"/></div>)}</div></div>)}</div>}

