import Link from "next/link";
import { DateTime } from "luxon";
import { getStaffSchedule } from "@/features/bookings/queries";
import { getCurrentProfile } from "@/lib/auth/session";
import { formatManilaTime } from "@/lib/format";
import { RealtimeRefresh } from "@/components/realtime-refresh";
import { getServerEnv } from "@/lib/env/server";
type Props={searchParams:Promise<{week?:string}>};
export const metadata={title:"Schedule"};
export const instant=false;
export default async function StaffSchedulePage({searchParams}:Props){const query=await searchParams;const profile=await getCurrentProfile();const requested=DateTime.fromISO(query.week??"",{zone:"Asia/Manila"});const week=(requested.isValid?requested:DateTime.now().setZone("Asia/Manila")).startOf("week");const days=Array.from({length:7},(_,i)=>week.plus({days:i}));const bookings=await getStaffSchedule(profile.id,{startsAt:week.toUTC().toJSDate(),endsAt:week.plus({days:7}).toUTC().toJSDate()});const env=getServerEnv();const topics=[...days.map(day=>`schedule:${day.toISODate()}`),"schedule:all"];return <div><RealtimeRefresh url={env.SUPABASE_URL} publishableKey={env.SUPABASE_PUBLISHABLE_KEY} topics={topics}/><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-800">Assigned appointments</p><h1 className="text-h1 mt-1">Schedule</h1></div><div className="flex gap-2"><Link href={`/portal/staff/schedule?week=${week.minus({weeks:1}).toISODate()}`} className="grid min-h-11 place-items-center rounded-xl border border-line bg-surface px-4 text-sm font-semibold">Previous</Link><Link href={`/portal/staff/schedule?week=${week.plus({weeks:1}).toISODate()}`} className="grid min-h-11 place-items-center rounded-xl border border-line bg-surface px-4 text-sm font-semibold">Next</Link></div></div><p className="tabular mt-3 text-ink-muted">{week.toFormat("d LLL")} – {week.plus({days:6}).toFormat("d LLL yyyy")}</p><div className="mt-7 space-y-5">{days.map(day=>{const values=bookings.filter(booking=>DateTime.fromJSDate(booking.requestedStartsAt,{zone:"utc"}).setZone("Asia/Manila").toISODate()===day.toISODate());return <section key={day.toISODate()}><h2 className="text-h3">{day.toFormat("cccc, d LLLL")}</h2><div className="mt-3 overflow-hidden rounded-2xl border border-line bg-surface">{values.length?values.map(booking=><Link key={booking.id} href={`/portal/staff/bookings/${booking.id}`} className="grid grid-cols-[72px_1fr] gap-3 border-b border-line p-4 last:border-0 hover:bg-brand-50 sm:grid-cols-[90px_1fr_auto]"><p className="tabular font-semibold text-brand-900">{formatManilaTime(booking.requestedStartsAt)}</p><div><p className="font-semibold">{booking.customerName}</p><p className="mt-1 text-sm text-ink-muted">{booking.services.map(x=>x.serviceName).join(", ")}</p></div><span className="col-start-2 text-sm font-semibold text-ink-subtle sm:col-start-auto">View details</span></Link>):<p className="p-4 text-sm text-ink-muted">No assignments.</p>}</div></section>})}</div></div>}
